# Generated by Django 3.0.5 on 2022-11-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(default='-', max_length=19)),
                ('emergency_type', models.CharField(default='-', max_length=7)),
                ('core_id', models.CharField(default='-', max_length=30)),
                ('latitude', models.FloatField(default=-1.0)),
                ('longitude', models.FloatField(default=-1.0)),
                ('accuracy', models.FloatField()),
                ('status', models.CharField(default='a', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.TextField(blank=True, max_length=500)),
                ('service', models.CharField(blank=True, max_length=8)),
                ('phone', models.CharField(blank=True, max_length=13)),
            ],
        ),
    ]
